### ISSUE TITLE
Got the following error

### ISSUE THREAD

**Issue by jemisa** [caspervonb/codeless#1] opened 2018-05-21 15:27 UTC
I pasted your example exactly,
but when I run it,
I got the following error
```

```

**Comment by caspervonb** [comment] 2018-05-21 15:32
That's odd!

I can't seem to reproduce it on Linux tho. Which operating system is this on?

**Comment by CameronFraser** [comment] 2018-05-21 16:05
I'm getting the same bug on

**Comment by Pebsie** [comment] 2018-05-21 16:07
Can confirm this is happening on Windows! 
I tried compiling codeless to be bootable from a USB and I also get a similar error:
`                                         
`
Any idea?

**Comment by caspervonb** [comment] 2018-05-23 01:14
Should be fixed in master.

**Comment by caspervonb** [comment] 2018-05-23 05:11
See #5, does this patch fix it? I just can't bother testing in Windows because I die a little inside every time I boot into it and the latest version I have is Windows ME.

**Comment by jemisa** [comment] 2018-05-23 13:59
Thank for the fix.

I'm actually running embedded linux on my air guitar.
#5 helped,  because I got this now
```



```
but as you would have noticed, still not working.

**Comment by Pebsie** [comment] 2018-08-25 12:27
I'm not actually getting that issue since #5 on Windows, might be a Linux/air guitar issue @jemisa.

**Closed as completed** 2019-06-16 16:29 UTC
Labels: bug, help wanted, wontfix
